### ISSUE TITLE
[BUG] site stops responding if left paused for an extended time

### ISSUE THREAD

**Issue by benmccann** [snuffyDev/Beatbump#137] opened 2023-01-17 22:13 UTC
**Describe the bug**
Sometimes I'll play music and then leave and come back and the site is no longer working. If I hit play nothing happens and I can't get any music to play. I have to kill the tab and re-open the site in a new tab

**To Reproduce**
1. Go to https://beatbump.ml/home
2. Start playing music
3. Hit pause after a few songs
4. Leave for a day
5. Come back and try to use the site again

**Expected behavior**
I should be able to pick back up where I left off

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome

**Comment by snuffyDev** [comment] 2023-01-17 23:14
Hmmmm... I'll attempt to reproduce this bug over the next couple of days. I should be able to get a decent enough sample size to narrow down any and all culprits.

My current hypothesis is: 

resuming playback after the app has been inactive for a long period of time (~4-8+ hours?) does have the risk of using an "expired" URL for the audio. 

YouTube uses a max-age on stream URLs so people can't freely access content without making an API request first.

If this turns out to be the cause of the problem you ran into, the solution would more than likely be to fetch a new URL if some sort of criteria is met.

I'll make comments on this issue if I have any questions, and with any status updates I have!

Thank you, and thank you for the great work you and everyone on the Svelte/SvelteKit teams have done!

**Comment by benmccann** [comment] 2023-01-18 15:54
Thanks!! In case it helps, when I hit play this morning after leaving it overnight, I got this error in the console:
```
GET https://rr1---sn-o097znzr.googlevideo.com/videoplayback?... net::ERR_ABORTED 403
```

**Comment by snuffyDev** [comment] 2023-01-19 08:47
After testing this a handful of times, and a quick sanity check by looking at the numerous issues posted in other YT-related projects (this issue goes over the same problem you described, but is caused by different circumstances https://github.com/ytdl-org/youtube-dl/issues/31247)

Good news is, Beatbump already has the ability to use the 'redirector' URLs - but they aren't actually used at the moment I believe, since Beatbump only will attempt playback using one URL.

I think the approach I'm gonna tackle this with is:
- Load "URL A"
- If playback fails, build "URL B" using the query params from "URL A"

Then, if things still are borked, attempt playback with "redirector" URL

I'll get crackin on this 😎🎉 

I'll reply with any further updates, or when the fix gets merged!

Thank you again!

**Comment by snuffyDev** [comment] 2023-01-20 04:52
Update: I'm testing out this function for building the fallback URL

```ts
// Helper to generate a fallback URL if the current src fails to play
function createFallbackUrl(currentUrl: string) {
	if (typeof currentUrl !== "string")
		throw Error(`Expected parameter 'currentUrl' to be a string, received ${currentUrl}`);
	const srcUrl = new URL(currentUrl);
	// example: [ rr4---sn-p5ql61yl , googlevideo , com ]
	const [subdomain, domain, ext] = srcUrl.hostname.split(".");

	const fvip = srcUrl.searchParams.get("fvip");
	// comma-separated list of fallback server hosts
	const mn = srcUrl.searchParams.get("mn");

	let [preDashes, postDashes] = subdomain.split("---");
	// step 1: replace digits in first part of subdomain with fvip
	preDashes = preDashes.replace(/\d/g, fvip);

	// step 2: use one of the fallback server names found in mn
	postDashes = mn.split(",")[1];

	srcUrl.hostname = `${`${preDashes}---${postDashes}`}.${domain}.${ext}`;

	return srcUrl.toString();
}
```

**Comment by snuffyDev** [comment] 2023-01-20 08:51
This Potential fix has been deployed on the main instance (https://beatbump.ml), will commit the changes on the dev branch soon.

I’ll test the reproduction method to see if it breaks still, hopefully it should be fixed (or almost fixed)!

**Comment by snuffyDev** [comment] 2023-01-21 06:48
## Results

The fallback URL works, it doesn't 403 anymore!
![image](https://user-images.githubusercontent.com/72365477/213846693-29bfd754-6c20-463f-aee2-97ed1ec9c02a.png)

...but it looks like there's still something that breaks (seems to be within Chrome?)

Good news is though, the app recovers from this now and is able to continue on as expected!


https://user-images.githubusercontent.com/72365477/213847539-3622b2ee-55b9-4cd3-8017-c03bcb10fee8.mp4


### Next steps

If whenever you have the time to try it out on production (https://beatbump.ml), I'd be interested to hear if the issue is fixed (ie. site still works, and doesn't crash after a day being idle)!

**Closed** 2023-01-28 20:59 UTC
Labels: bug
