### ISSUE TITLE
Cloudflare workers: could not find index.html in your content namespace

### ISSUE THREAD

**Issue by dahyuk0413** [snuffyDev/Beatbump#2] opened 2021-08-13 03:18 UTC
I tried to setup my beatbump site, but it keeps saying 'could not find index.html in your content namespace'.
Here is my wrangler.toml

name = "beatbump"
type = "webpack"
route = 'censored'
zone_id = 'censored'
account_id = 'censored'
usage_model = ''
compatibility_flags = []
workers_dev = true
[site]
bucket = "./static"
entry-point = "./workers-site"

Is the bucket directory wrong? You can close this issue if this issue cannot be solved.

Thanks for your support,

Dahyuk

**Comment by dahyuk0413** [comment] 2021-08-13 03:28
And here is the log when I tried to run 'npm run deploy'

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'deploy' ]
2 info using npm@6.14.14
3 info using node@v14.17.4
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle beatbump@0.0.8~predeploy: beatbump@0.0.8
6 info lifecycle beatbump@0.0.8~deploy: beatbump@0.0.8
7 verbose lifecycle beatbump@0.0.8~deploy: unsafe-perm in lifecycle true
8 verbose lifecycle beatbump@0.0.8~deploy: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/dahyuk/Beatbump/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle beatbump@0.0.8~deploy: CWD: /Users/dahyuk/Beatbump
10 silly lifecycle beatbump@0.0.8~deploy: Args: [ '-c', 'npm run build && wrangler publish' ]
11 silly lifecycle beatbump@0.0.8~deploy: Returned: code: 1  signal: null
12 info lifecycle beatbump@0.0.8~deploy: Failed to exec deploy script
13 verbose stack Error: beatbump@0.0.8 deploy: `npm run build && wrangler publish`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid beatbump@0.0.8
15 verbose cwd /Users/dahyuk/Beatbump
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
18 verbose node v14.17.4
19 verbose npm  v6.14.14
20 error code ELIFECYCLE
21 error errno 1
22 error beatbump@0.0.8 deploy: `npm run build && wrangler publish`
22 error Exit status 1
23 error Failed at the beatbump@0.0.8 deploy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by dahyuk0413** [comment] 2021-08-13 03:30
[load-fallback] Could not load /Users/dahyuk/Beatbump/src/lib/_parsers (imported by src/lib/stores/list.ts): ENOENT: no such file or directory, open '/Users/dahyuk/Beatbump/src/lib/_parsers'
> Could not load /Users/dahyuk/Beatbump/src/lib/_parsers (imported by src/lib/stores/list.ts): ENOENT: no such file or directory, open '/Users/dahyuk/Beatbump/src/lib/_parsers'
Error: Could not load /Users/dahyuk/Beatbump/src/lib/_parsers (imported by src/lib/stores/list.ts): ENOENT: no such file or directory, open '/Users/dahyuk/Beatbump/src/lib/_parsers'

Is this the error occured by src/lib/_parsers?

**Comment by dahyuk0413** [comment] 2021-08-13 03:40
> html:/Users/dahyuk/Beatbump/src/lib/components/Icon/Icon.svelte:6:17: error: Expected ";" but found ":"
    6 │   export let width: string | number = 0
      ╵                   ^

 > html:/Users/dahyuk/Beatbump/src/lib/components/Player/Player.svelte:54:18: error: Expected ";" but found ":"
    54 │   let DropdownItems: Array<any>
       ╵                    ^

Also found this error.

**Comment by dahyuk0413** [comment] 2021-08-13 03:43
> html:/Users/dahyuk/Beatbump/src/lib/components/Icon/Icon.svelte:6:17: error: Expected ";" but found ":"
    6 │   export let width: string | number = 0
      ╵                   ^

 > html:/Users/dahyuk/Beatbump/src/lib/components/Player/Player.svelte:24:13: error: Expected ";" but found ":"
    24 │   const player: HTMLAudioElement = new Audio()

**Comment by dahyuk0413** [comment] 2021-08-13 04:53
@snuffyDev Is there any fixes right now?

**Comment by snuffyDev** [comment] 2021-08-13 09:51
> @snuffyDev Is there any fixes right now?

Yes my bad for the late reply, thank you for the issue. The problem is a file I accidentally privated. Let me verify my latest commit and I’ll get back to you as soon as I get this sorted

**Comment by snuffyDev** [comment] 2021-08-13 10:17
I just did a full deploy on a fresh Cloudflare account, with a cloned repo and it deployed for me. There was a file I did have privated but has since been deleted as of a few commits ago. For the fresh repo I used to test, this is the ```wrangler.toml``` I used.
```
name = "beatbump"
type = 'webpack'
account_id = '###'
route = ''
zone_id = ''
usage_model = ''
workers_dev = true
target_type = "webpack"

[site]
bucket = "./build"
entry-point = "./workers-site"
```
Note the bucket being "./build", as I see yours is "./static". Perhaps that was the issue? As for the other errors I didn't get those as far as I can tell during the deployment.

The docs are still a work in progress, but don't forget to [read the note](https://snuffydev.github.io/Beatbump/#/docs/introduction/deploying) at the top about the ```.env``` setup. It's an important step as well, because it's for the Content-Security Policy.

Feel free to let me know if there are any further issues, or if this problem persists. Appreciate you trying out Beatbump!

**Comment by snuffyDev** [comment] 2021-08-18 02:11
Assuming the problem was resolved I’m going to close this, feel free to open another if anything comes up!

**Closed by snuffyDev** 2021-08-18 02:11 UTC

**Comment by snuffyDev** [comment] 2021-08-18 10:36
As a follow up, I just now realized what was causing those errors, and I can't believe I overlooked them entirely! Got so used to Typescript I forgot to update some old components to have ```<script lang="ts">```. I apologize about that! Should have a commit pushed within the next hour or so with a bunch of updates and a for-sure fix!
